#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely.

rip() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I hate the kill command" && rip' SIGTERM
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'rip' SIGQUIT
done
